require("settings")
require("mappings")
require("colorschemes-config.nordfox")
require("lualine-config")
require("packer-config")
require("nvim-tree-config")
require("barbar-config")
require("treesitter-config")
require("comment-config")
require("telescope-config")
require("blankline-config")
require("toggleterm-config")

--> lsp modules
require("lsp-config.language-servers")
require("lsp-config.nvim-cmp")
require("lsp-config.null-ls")
require("lsp-config.autopairs")
require("lsp-config.lsp-installer")
